In [6]:
import pandas as pd

In [7]:
vac1516="dataView1340_3.xls"
vac1617="dataView2065_3.xls"
vac1718="dataView2164_3.xls"
vac1819="dataView2246_3.xls"

vac1516_df=pd.read_excel(vac1516)
vac1617_df=pd.read_excel(vac1617)
vac1718_df=pd.read_excel(vac1718)
vac1819_df=pd.read_excel(vac1819)

In [9]:
vac1516_df.head(20)
#del vac1516_df["Unnamed: 2"]

,Unnamed: 0,Influenza vaccination (General Population) - Age,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,...,Unnamed: 99,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108
0,NaN,≥6 months,NaN,NaN,NaN,NaN,6 months - 17 years,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"Other or multiple races, non-Hispanic",NaN,NaN,NaN,NaN,NaN
1,Names,2015-16,UL,CI,SAMPLE,TARGET,2015-16,LL,UL,CI,...,UL,CI,SAMPLE,TARGET,2015-16,LL,UL,CI,SAMPLE,TARGET
2,Alabama,43.9,45.9,(±2.0),7822,70,61.9,58,65.8,(±3.9),...,70.5,(±9.4),244,70,45.8,34.8,56.8,(±11.0)‡,358,70
3,Alaska,37.9,40.3,(±2.4),4740,70,47.9,44.1,51.7,(±3.8),...,45.3,(±9.8),266,70,37.2,31.8,42.6,(±5.4),1171,70
4,Arizona,41.5,43.2,(±1.7),9739,70,52,48.3,55.7,(±3.7),...,42.9,(±3.9),1727,70,46.9,41.4,52.4,(±5.5),887,70
5,Arkansas,45.4,47.8,(±2.4),5694,70,66.4,62.5,70.3,(±3.9),...,64.5,(±9.0),312,70,39.6,28.5,50.7,(±11.1)‡,342,70
6,California,43.7,46.1,(±2.4),9488,70,59.9,56.3,63.5,(±3.6),...,45,(±3.9),2758,70,43,38.2,47.8,(±4.8),1447,70
7,Colorado,49.1,50.8,(±1.7),10600,70,62.4,58.2,66.6,(±4.2),...,54.2,(±4.0),1634,70,48.5,41.7,55.3,(±6.8),543,70
8,Connecticut,52.6,54.3,(±1.7),11758,70,70.5,67.1,73.9,(±3.4),...,57.9,(±5.4),1223,70,52.6,45.7,59.5,(±6.9),646,70
9,Delaware,50.5,53.4,(±2.9),5144,70,69.2,63.9,74.5,(±5.3),...,58.3,(±6.4),561,70,51.7,41.6,61.8,(±10.1)‡,421,70
10,District of Columbia,47.6,51.6,(±4.0),4624,70,69.9,65.1,74.7,(±4.8),...,66.1,(±12.1)‡,423,70,49.2,33.6,64.8,(±15.6)‡,380,70
11,Florida,39.5,40.9,(±1.4),15430,70,47.9,44.5,51.3,(±3.4),...,36.3,(±3.2),2161,70,40.8,34.9,46.7,(±5.9),744,70
12,Georgia,41.2,43.4,(±2.2),5874,70,51.3,48,54.6,(±3.3),...,48,(±7.0),468,70,39.5,31.7,47.3,(±7.8),424,70
13,Hawaii,50.2,54,(±3.8),7604,70,71.8,67.8,75.8,(±4.0),...,66.2,(±10.3)‡,666,70,51.2,45.7,56.7,(±5.5),4625,70
14,Idaho,39.2,41.2,(±2.0),6052,70,45.4,40.6,50.2,(±4.8),...,41.7,(±6.9),494,70,43.9,34.2,53.6,(±9.7),257,70
15,Illinois,42.9,45.1,(±2.2),7893,70,55.3,52.4,58.2,(±2.9),...,56.2,(±6.6),1309,70,38,31.7,44.3,(±6.3),692,70
16,Indiana,43.2,44.9,(±1.7),6760,70,51.6,47.9,55.3,(±3.7),...,51.1,(±7.3),362,70,47.3,38.3,56.3,(±9.0),328,70
17,Iowa,51.8,53.5,(±1.7),7436,70,59.1,55.7,62.5,(±3.4),...,59.4,(±7.7),346,70,50,40.5,59.5,(±9.5),255,70
18,Kansas,44.4,45.9,(±1.5),12767,70,55.6,51.5,59.7,(±4.1),...,47.1,(±5.3),921,70,40.9,34,47.8,(±6.9),587,70
19,Kentucky,44.2,45.9,(±1.7),8733,70,51.7,47.9,55.5,(±3.8),...,59,(±9.8),211,70,36.6,29.5,43.7,(±7.1),438,70

In [11]:
vac1516_df.head()

cleaned1516=vac1516_df.drop(columns=["Unnamed: 0","Influenza vaccination (General Population) - Age",
                        "Unnamed: 3","Unnamed: 4","Unnamed: 6","Unnamed: 99","Unnamed: 100","Unnamed: 101","Unnamed: 102","Unnamed: 103","Unnamed: 104",
                        "Unnamed: 105","Unnamed: 106","Unnamed: 7","Unnamed: 8","Unnamed: 9","Unnamed: 10","Unnamed: 12","Unnamed: 13","Unnamed: 14"
                                    ,"Unnamed: 15","Unnamed: 16","Unnamed: 18","Unnamed: 19","Unnamed: 20","Unnamed: 21","Unnamed: 22",
                                    "Unnamed: 24","Unnamed: 25","Unnamed: 26","Unnamed: 27","Unnamed: 28",
                                    "Unnamed: 30","Unnamed: 31","Unnamed: 32","Unnamed: 33","Unnamed: 34",
                                    "Unnamed: 36","Unnamed: 37","Unnamed: 38","Unnamed: 39","Unnamed: 40",
                                    "Unnamed: 42","Unnamed: 43","Unnamed: 44","Unnamed: 45","Unnamed: 46",
                                    "Unnamed: 48","Unnamed: 49","Unnamed: 50","Unnamed: 51","Unnamed: 52",
                                    "Unnamed: 54","Unnamed: 55","Unnamed: 56","Unnamed: 57","Unnamed: 58",
                                    "Unnamed: 91","Unnamed: 92","Unnamed: 93","Unnamed: 94","Unnamed: 95",
                                    "Unnamed: 60","Unnamed: 61","Unnamed: 62","Unnamed: 63","Unnamed: 64",
                                    "Unnamed: 66","Unnamed: 67","Unnamed: 68","Unnamed: 69","Unnamed: 70",
                                    "Unnamed: 72","Unnamed: 73","Unnamed: 74","Unnamed: 75","Unnamed: 76",
                                    "Unnamed: 78","Unnamed: 79","Unnamed: 80","Unnamed: 81","Unnamed: 82",
                                    "Unnamed: 84","Unnamed: 86","Unnamed: 87","Unnamed: 88",
                                    "Unnamed: 89","Unnamed: 90","Unnamed: 96","Unnamed: 97","Unnamed: 98",
                                    "Unnamed: 107","Unnamed: 108", "Influenza vaccination (General Population) - Race/ethnicity"])

cleaned1516=cleaned1516.drop([0,1],axis=0)
cleaned1516.head()

cleaned1516.rename(columns={"Unnamed: 0":"Location of Immunization"},inplace=True)
cleaned1516.rename(columns={"Unnamed: 5":"≥ 6 months"},inplace=True)
cleaned1516.rename(columns={"Unnamed: 11":"6 months - 17 years"},inplace=True)
cleaned1516.rename(columns={"Unnamed: 17":"6 months - 4 years"},inplace=True)
cleaned1516.rename(columns={"Unnamed: 23":"5 - 12 years"},inplace=True)
cleaned1516.rename(columns={"Unnamed: 29":"13 - 17 years"},inplace=True)
cleaned1516.rename(columns={"Unnamed: 35":"≥ 18 years"},inplace=True)
cleaned1516.rename(columns={"Unnamed: 41":"18 - 64 years"},inplace=True)
cleaned1516.rename(columns={"Unnamed: 59":"18 - 49 years"},inplace=True)
cleaned1516.rename(columns={"Unnamed: 77":"50 -64 years"},inplace=True)
cleaned1516.rename(columns={"Unnamed: 83":"≥ 65 years"},inplace=True)

del cleaned1516["Unnamed: 47"]
del cleaned1516["Unnamed: 53"]
del cleaned1516["Unnamed: 65"]
del cleaned1516["Unnamed: 71"]


cleaned1516.insert(0, 'Flu Season', '2015-2016')

In [12]:
cleaned1516.head(20)

,Flu Season,≥ 6 months,6 months - 17 years,6 months - 4 years,5 - 12 years,13 - 17 years,≥ 18 years,18 - 64 years,18 - 49 years,50 -64 years,≥ 65 years
2,2015-2016,7822,2375,720,1121,534,5447,3719,1992,1727,1728
3,2015-2016,4740,2287,681,955,651,2453,1801,946,855,652
4,2015-2016,9739,2418,678,983,757,7321,3933,1859,2074,3388
5,2015-2016,5694,1896,566,797,533,3798,2017,850,1167,1781
6,2015-2016,9488,2437,834,1020,583,7051,5349,3452,1897,1702
7,2015-2016,10600,1846,584,799,463,8754,5807,3057,2750,2947
8,2015-2016,11758,2344,706,1110,528,9414,5764,2620,3144,3650
9,2015-2016,5144,2089,606,941,542,3055,1969,992,977,1086
10,2015-2016,4624,2425,833,1007,585,2199,1255,542,713,944
11,2015-2016,15430,2354,725,1015,614,13076,7698,3929,3769,5378
12,2015-2016,5874,2466,788,1131,547,3408,2140,1102,1038,1268
13,2015-2016,7604,2126,656,964,506,5478,3625,1888,1737,1853
14,2015-2016,6052,1669,493,702,474,4383,2750,1413,1337,1633
15,2015-2016,7893,4387,1347,1832,1208,3506,2338,1302,1036,1168
16,2015-2016,6760,1938,575,845,518,4822,2938,1448,1490,1884
17,2015-2016,7436,2242,671,1040,531,5194,3294,1616,1678,1900
18,2015-2016,12767,1675,509,670,496,11092,7217,3739,3478,3875
19,2015-2016,8733,1934,609,864,461,6799,4664,2383,2281,2135
20,2015-2016,6240,2208,626,965,617,4032,2436,1124,1312,1596
21,2015-2016,9654,2182,615,1023,544,7472,4631,2097,2534,2841

In [88]:
vac1617_df.head()
cleaned1617=vac1617_df.drop(columns=["Unnamed: 2","Influenza vaccination (General Population) - Age",
                        "Unnamed: 3","Unnamed: 4","Unnamed: 6","Unnamed: 99","Unnamed: 100","Unnamed: 101","Unnamed: 102","Unnamed: 103","Unnamed: 104",
                        "Unnamed: 105","Unnamed: 106","Unnamed: 7","Unnamed: 8","Unnamed: 9","Unnamed: 10","Unnamed: 12","Unnamed: 13","Unnamed: 14"
                                    ,"Unnamed: 15","Unnamed: 16","Unnamed: 18","Unnamed: 19","Unnamed: 20","Unnamed: 21","Unnamed: 22",
                                    "Unnamed: 24","Unnamed: 25","Unnamed: 26","Unnamed: 27","Unnamed: 28",
                                    "Unnamed: 30","Unnamed: 31","Unnamed: 32","Unnamed: 33","Unnamed: 34",
                                    "Unnamed: 36","Unnamed: 37","Unnamed: 38","Unnamed: 39","Unnamed: 40",
                                    "Unnamed: 42","Unnamed: 43","Unnamed: 44","Unnamed: 45","Unnamed: 46",
                                    "Unnamed: 48","Unnamed: 49","Unnamed: 50","Unnamed: 51","Unnamed: 52",
                                    "Unnamed: 54","Unnamed: 55","Unnamed: 56","Unnamed: 57","Unnamed: 58",
                                    "Unnamed: 91","Unnamed: 92","Unnamed: 93","Unnamed: 94","Unnamed: 95",
                                    "Unnamed: 60","Unnamed: 61","Unnamed: 62","Unnamed: 63","Unnamed: 64",
                                    "Unnamed: 66","Unnamed: 67","Unnamed: 68","Unnamed: 69","Unnamed: 70",
                                    "Unnamed: 72","Unnamed: 73","Unnamed: 74","Unnamed: 75","Unnamed: 76",
                                    "Unnamed: 78","Unnamed: 79","Unnamed: 80","Unnamed: 81","Unnamed: 82",
                                    "Unnamed: 84","Unnamed: 86","Unnamed: 87","Unnamed: 88",
                                    "Unnamed: 89","Unnamed: 90","Unnamed: 96","Unnamed: 97","Unnamed: 98",
                                    "Unnamed: 107","Unnamed: 108", "Influenza vaccination (General Population) - Race/ethnicity"])

cleaned1617=cleaned1617.drop([0,1],axis=0)
cleaned1617.head()

cleaned1617.rename(columns={"Unnamed: 0":"Location of Immunization"},inplace=True)
cleaned1617.rename(columns={"Unnamed: 5":"≥ 6 months"},inplace=True)
cleaned1617.rename(columns={"Unnamed: 11":"6 months - 17 years"},inplace=True)
cleaned1617.rename(columns={"Unnamed: 17":"6 months - 4 years"},inplace=True)
cleaned1617.rename(columns={"Unnamed: 23":"5 - 12 years"},inplace=True)
cleaned1617.rename(columns={"Unnamed: 29":"13 - 17 years"},inplace=True)
cleaned1617.rename(columns={"Unnamed: 35":"≥ 18 years"},inplace=True)
cleaned1617.rename(columns={"Unnamed: 41":"18 - 64 years"},inplace=True)
cleaned1617.rename(columns={"Unnamed: 59":"18 - 49 years"},inplace=True)
cleaned1617.rename(columns={"Unnamed: 77":"50 -64 years"},inplace=True)
cleaned1617.rename(columns={"Unnamed: 83":"≥ 65 years"},inplace=True)

del cleaned1617["Unnamed: 47"]
del cleaned1617["Unnamed: 53"]
del cleaned1617["Unnamed: 65"]
del cleaned1617["Unnamed: 71"]

cleaned1617.insert(0, 'Flu Season', '2016-2017')

In [89]:
cleaned1617.head()

,Flu Season,Location of Immunization,≥ 6 months,6 months - 17 years,6 months - 4 years,5 - 12 years,13 - 17 years,≥ 18 years,18 - 64 years,18 - 49 years,50 -64 years,≥ 65 years
2,2016-2017,Alabama,7901,2555,757,1196,602,5346,3393,1774,1619,1953
3,2016-2017,Alaska,4998,2238,688,971,579,2760,1989,980,1009,771
4,2016-2017,Arizona,11261,2357,706,1030,621,8904,4950,2486,2464,3954
5,2016-2017,Arkansas,6418,2303,691,1027,585,4115,2075,896,1179,2040
6,2016-2017,California,8010,3095,1059,1348,688,4915,3726,2436,1290,1189

In [92]:
vac1718_df.head()
cleaned1718=vac1718_df.drop(columns=["Unnamed: 2","Influenza vaccination (General Population) - Age",
                        "Unnamed: 3","Unnamed: 4","Unnamed: 6","Unnamed: 99","Unnamed: 100","Unnamed: 101","Unnamed: 102","Unnamed: 103","Unnamed: 104",
                        "Unnamed: 105","Unnamed: 106","Unnamed: 7","Unnamed: 8","Unnamed: 9","Unnamed: 10","Unnamed: 12","Unnamed: 13","Unnamed: 14"
                                    ,"Unnamed: 15","Unnamed: 16","Unnamed: 18","Unnamed: 19","Unnamed: 20","Unnamed: 21","Unnamed: 22",
                                    "Unnamed: 24","Unnamed: 25","Unnamed: 26","Unnamed: 27","Unnamed: 28",
                                    "Unnamed: 30","Unnamed: 31","Unnamed: 32","Unnamed: 33","Unnamed: 34",
                                    "Unnamed: 36","Unnamed: 37","Unnamed: 38","Unnamed: 39","Unnamed: 40",
                                    "Unnamed: 42","Unnamed: 43","Unnamed: 44","Unnamed: 45","Unnamed: 46",
                                    "Unnamed: 48","Unnamed: 49","Unnamed: 50","Unnamed: 51","Unnamed: 52",
                                    "Unnamed: 54","Unnamed: 55","Unnamed: 56","Unnamed: 57","Unnamed: 58",
                                    "Unnamed: 91","Unnamed: 92","Unnamed: 93","Unnamed: 94","Unnamed: 95",
                                    "Unnamed: 60","Unnamed: 61","Unnamed: 62","Unnamed: 63","Unnamed: 64",
                                    "Unnamed: 66","Unnamed: 67","Unnamed: 68","Unnamed: 69","Unnamed: 70",
                                    "Unnamed: 72","Unnamed: 73","Unnamed: 74","Unnamed: 75","Unnamed: 76",
                                    "Unnamed: 78","Unnamed: 79","Unnamed: 80","Unnamed: 81","Unnamed: 82",
                                    "Unnamed: 84","Unnamed: 86","Unnamed: 87","Unnamed: 88",
                                    "Unnamed: 89","Unnamed: 90","Unnamed: 96","Unnamed: 97","Unnamed: 98",
                                    "Unnamed: 107","Unnamed: 108", "Influenza vaccination (General Population) - Race/ethnicity"])

cleaned1718=cleaned1718.drop([0,1],axis=0)
cleaned1718.head()

cleaned1718.rename(columns={"Unnamed: 0":"Location of Immunization"},inplace=True)
cleaned1718.rename(columns={"Unnamed: 5":"≥ 6 months"},inplace=True)
cleaned1718.rename(columns={"Unnamed: 11":"6 months - 17 years"},inplace=True)
cleaned1718.rename(columns={"Unnamed: 17":"6 months - 4 years"},inplace=True)
cleaned1718.rename(columns={"Unnamed: 23":"5 - 12 years"},inplace=True)
cleaned1718.rename(columns={"Unnamed: 29":"13 - 17 years"},inplace=True)
cleaned1718.rename(columns={"Unnamed: 35":"≥ 18 years"},inplace=True)
cleaned1718.rename(columns={"Unnamed: 41":"18 - 64 years"},inplace=True)
cleaned1718.rename(columns={"Unnamed: 59":"18 - 49 years"},inplace=True)
cleaned1718.rename(columns={"Unnamed: 77":"50 -64 years"},inplace=True)
cleaned1718.rename(columns={"Unnamed: 83":"≥ 65 years"},inplace=True)

del cleaned1718["Unnamed: 47"]
del cleaned1718["Unnamed: 53"]
del cleaned1718["Unnamed: 65"]
del cleaned1718["Unnamed: 71"]

cleaned1718.insert(0, 'Flu Season', '2017-2018')

In [93]:
cleaned1718.head()

,Flu Season,Location of Immunization,≥ 6 months,6 months - 17 years,6 months - 4 years,5 - 12 years,13 - 17 years,≥ 18 years,18 - 64 years,18 - 49 years,50 -64 years,≥ 65 years
2,2017-2018,Alabama,7547,2671,854,1224,593,4876,3030,1560,1470,1846
3,2017-2018,Alaska,3690,1752,564,719,469,1938,1311,718,593,627
4,2017-2018,Arizona,12285,2358,740,1120,498,9927,5985,3168,2817,3942
5,2017-2018,Arkansas,6287,2129,647,925,557,4158,2031,909,1122,2127
6,2017-2018,California,10838,2355,809,950,596,8483,6643,4380,2263,1840

In [99]:
vac1819_df.head()
cleaned1819=vac1819_df.drop(columns=["Unnamed: 2","Influenza vaccination (General Population) - Age",
                        "Unnamed: 3","Unnamed: 4","Unnamed: 6","Unnamed: 99","Unnamed: 100","Unnamed: 101","Unnamed: 102","Unnamed: 103","Unnamed: 104",
                        "Unnamed: 105","Unnamed: 106","Unnamed: 7","Unnamed: 8","Unnamed: 9","Unnamed: 10","Unnamed: 12","Unnamed: 13","Unnamed: 14"
                                    ,"Unnamed: 15","Unnamed: 16","Unnamed: 18","Unnamed: 19","Unnamed: 20","Unnamed: 21","Unnamed: 22",
                                    "Unnamed: 24","Unnamed: 25","Unnamed: 26","Unnamed: 27","Unnamed: 28",
                                    "Unnamed: 30","Unnamed: 31","Unnamed: 32","Unnamed: 33","Unnamed: 34",
                                    "Unnamed: 36","Unnamed: 37","Unnamed: 38","Unnamed: 39","Unnamed: 40",
                                    "Unnamed: 42","Unnamed: 43","Unnamed: 44","Unnamed: 45","Unnamed: 46",
                                    "Unnamed: 48","Unnamed: 49","Unnamed: 50","Unnamed: 51","Unnamed: 52",
                                    "Unnamed: 54","Unnamed: 55","Unnamed: 56","Unnamed: 57","Unnamed: 58",
                                    "Unnamed: 91","Unnamed: 92","Unnamed: 93","Unnamed: 94","Unnamed: 95",
                                    "Unnamed: 60","Unnamed: 61","Unnamed: 62","Unnamed: 63","Unnamed: 64",
                                    "Unnamed: 66","Unnamed: 67","Unnamed: 68","Unnamed: 69","Unnamed: 70",
                                    "Unnamed: 72","Unnamed: 73","Unnamed: 74","Unnamed: 75","Unnamed: 76",
                                    "Unnamed: 78","Unnamed: 79","Unnamed: 80","Unnamed: 81","Unnamed: 82",
                                    "Unnamed: 84","Unnamed: 86","Unnamed: 87","Unnamed: 88",
                                    "Unnamed: 89","Unnamed: 90","Unnamed: 96","Unnamed: 97","Unnamed: 98",
                                    "Unnamed: 107","Unnamed: 108", "Influenza vaccination (General Population) - Race/ethnicity"])

cleaned1819=cleaned1819.drop([0,1],axis=0)


cleaned1819.rename(columns={"Unnamed: 0":"Location of Immunization"},inplace=True)
cleaned1819.rename(columns={"Unnamed: 5":"≥ 6 months"},inplace=True)
cleaned1819.rename(columns={"Unnamed: 11":"6 months - 17 years"},inplace=True)
cleaned1819.rename(columns={"Unnamed: 17":"6 months - 4 years"},inplace=True)
cleaned1819.rename(columns={"Unnamed: 23":"5 - 12 years"},inplace=True)
cleaned1819.rename(columns={"Unnamed: 29":"13 - 17 years"},inplace=True)
cleaned1819.rename(columns={"Unnamed: 35":"≥ 18 years"},inplace=True)
cleaned1819.rename(columns={"Unnamed: 41":"18 - 64 years"},inplace=True)
cleaned1819.rename(columns={"Unnamed: 59":"18 - 49 years"},inplace=True)
cleaned1819.rename(columns={"Unnamed: 77":"50 -64 years"},inplace=True)
cleaned1819.rename(columns={"Unnamed: 83":"≥ 65 years"},inplace=True)

del cleaned1819["Unnamed: 47"]
del cleaned1819["Unnamed: 53"]
del cleaned1819["Unnamed: 65"]
del cleaned1819["Unnamed: 71"]

cleaned1819.insert(0, 'Flu Season', '2018-2019')

In [108]:
last10=cleaned1819.tail(10)

last10.head(10
           )

,Flu Season,Location of Immunization,≥ 6 months,6 months - 17 years,6 months - 4 years,5 - 12 years,13 - 17 years,≥ 18 years,18 - 64 years,18 - 49 years,50 -64 years,≥ 65 years
54,2018-2019,Region 1,47287,13207,4089,5855,3263,34080,20444,9776,10668,13636
55,2018-2019,Region 2,26785,8308,2924,3509,1875,18477,12114,6642,5472,6363
56,2018-2019,Region 3,55570,21795,7411,10028,4356,33775,21387,11148,10239,12388
57,2018-2019,Region 4,68549,22852,7511,10301,5040,45697,28066,15319,12747,17631
58,2018-2019,Region 5,55393,16318,5324,6990,4004,39075,24966,13599,11367,14109
59,2018-2019,Region 6,45524,21098,7190,7649,6259,24426,15024,8385,6639,9402
60,2018-2019,Region 7,39108,7748,2527,3190,2031,31360,19462,10761,8701,11898
61,2018-2019,Region 8,46072,11625,3857,4907,2861,34447,22057,12613,9444,12390
62,2018-2019,Region 9,30862,9216,3125,3786,2305,21646,14279,8525,5754,7367
63,2018-2019,Region 10,26356,7191,2290,2926,1975,19165,12294,7071,5223,6871

In [ ]:
cleaned1819.to_csv (r'vaccine1819data.csv', index = False, header=True)